# Generated by Django 6.0.2 on 2026-02-21 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('institutes', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_number', models.CharField(max_length=50, unique=True, verbose_name='Permission Number')),
                ('program_type', models.CharField(choices=[('diploma', 'Diploma'), ('course', 'Course')], max_length=20, verbose_name='Program Type')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Issue Date')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20, verbose_name='Status')),
                ('pdf_file', models.FileField(blank=True, upload_to='permissions/pdfs/%Y/%m/', verbose_name='PDF File')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='clients.client', verbose_name='Client')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='programs.course', verbose_name='Course')),
                ('diploma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='programs.diploma', verbose_name='Diploma')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='institutes.institute', verbose_name='Institute')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_issued', to=settings.AUTH_USER_MODEL, verbose_name='Issued By')),
            ],
            options={
                'verbose_name': 'Permission Slip',
                'verbose_name_plural': 'Permission Slips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_content', models.TextField(help_text='HTML content for PDF header', verbose_name='Header Content')),
                ('body_content', models.TextField(help_text='HTML content for PDF body', verbose_name='Body Content')),
                ('footer_content', models.TextField(help_text='HTML content for PDF footer', verbose_name='Footer Content')),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS styles for PDF', verbose_name='Custom CSS')),
                ('page_size', models.CharField(default='A4', max_length=20, verbose_name='Page Size')),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=20, verbose_name='Orientation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('institute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_template', to='institutes.institute', verbose_name='Institute')),
            ],
            options={
                'verbose_name': 'Permission Template',
                'verbose_name_plural': 'Permission Templates',
            },
        ),
    ]
