# Generated by Django 5.2.11 on 2026-02-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionslip',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف'),
        ),
        migrations.AddField(
            model_name='permissiontemplate',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='محذوف'),
        ),
    ]
