# Generated by Django 5.2.11 on 2026-04-26 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_clients_cli_nationa_62e969_idx_and_more'),
        ('institutes', '0003_institute_background_img_and_more'),
        ('permissions', '0002_permissionslip_is_deleted_and_more'),
        ('programs', '0003_course_programs_co_code_194299_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='permissionslip',
            index=models.Index(fields=['permission_number'], name='permissions_permiss_03eea3_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionslip',
            index=models.Index(fields=['client', 'status'], name='permissions_client__defeaa_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionslip',
            index=models.Index(fields=['institute', 'status'], name='permissions_institu_f3259d_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionslip',
            index=models.Index(fields=['issued_by'], name='permissions_issued__8c3e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionslip',
            index=models.Index(fields=['issue_date'], name='permissions_issue_d_4c917d_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionslip',
            index=models.Index(fields=['expiry_date'], name='permissions_expiry__621209_idx'),
        ),
        migrations.AddIndex(
            model_name='permissionslip',
            index=models.Index(fields=['is_deleted'], name='permissions_is_dele_aeca07_idx'),
        ),
        migrations.AddIndex(
            model_name='permissiontemplate',
            index=models.Index(fields=['institute'], name='permissions_institu_a46f30_idx'),
        ),
    ]
