# Generated by Django 5.2.11 on 2026-08-04 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0003_permissionslip_permissions_permiss_03eea3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionslip',
            name='issued_from_public',
            field=models.BooleanField(default=False, verbose_name='Issued From Public Portal'),
        ),
        migrations.AddField(
            model_name='permissionslip',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Referral Code'),
        ),
        migrations.AddField(
            model_name='permissionslip',
            name='referral_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Referral Employee'),
        ),
    ]
