# Generated by Django 5.2.11 on 2026-08-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_permissionslip_issued_from_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionslip',
            name='study_mode',
            field=models.CharField(blank=True, choices=[('offline', 'حضوري'), ('online', 'أونلاين')], max_length=20, verbose_name='Study Mode'),
        ),
    ]
