# Generated by Django 5.2.11 on 2026-08-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0005_permissionslip_study_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiontemplate',
            name='font_family',
            field=models.CharField(choices=[('arial', 'Arial (افتراضي)'), ('cairo', 'Cairo (عربي حديث)')], default='arial', help_text='Font used in the generated PDF', max_length=20, verbose_name='Font'),
        ),
    ]
