# Generated by Django 5.2.11 on 2026-04-26 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_is_deleted'),
        ('institutes', '0003_institute_background_img_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['national_id'], name='clients_cli_nationa_62e969_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['institute', 'status'], name='clients_cli_institu_29f918_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['registered_by'], name='clients_cli_registe_e3335b_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['registration_date'], name='clients_cli_registr_ce1051_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_deleted'], name='clients_cli_is_dele_4bb44e_idx'),
        ),
    ]
