# Generated by Django 5.2.11 on 2026-08-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_clients_cli_nationa_62e969_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='client',
            name='sector',
            field=models.CharField(blank=True, choices=[('military', 'عسكري'), ('civil', 'مدني'), ('retired', 'متقاعد'), ('other', 'أخرى')], max_length=20, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
    ]
