# Generated by Django 5.2.11 on 2026-08-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_city_client_sector_alter_client_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sector',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sector'),
        ),
    ]
