# Generated by Django 6.0.2 on 2026-02-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Institute Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Institute Code')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='License Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, upload_to='institutes/logos/', verbose_name='Logo')),
                ('header_image', models.ImageField(blank=True, upload_to='institutes/headers/', verbose_name='Header Image')),
                ('footer_text', models.TextField(blank=True, verbose_name='Footer Text')),
                ('pdf_template', models.TextField(blank=True, help_text='Custom HTML template for permission PDF', verbose_name='PDF Template')),
                ('signature_image', models.ImageField(blank=True, upload_to='institutes/signatures/', verbose_name='Signature Image')),
                ('stamp_image', models.ImageField(blank=True, upload_to='institutes/stamps/', verbose_name='Stamp Image')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Institute',
                'verbose_name_plural': 'Institutes',
                'ordering': ['name'],
            },
        ),
    ]
