# Generated by Django 5.2.11 on 2026-04-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0002_institute_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='background_img',
            field=models.ImageField(blank=True, upload_to='institutes/background/', verbose_name='background Image'),
        ),
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['code'], name='institutes__code_2d3b91_idx'),
        ),
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['status'], name='institutes__status_b5774c_idx'),
        ),
        migrations.AddIndex(
            model_name='institute',
            index=models.Index(fields=['city', 'status'], name='institutes__city_8051c5_idx'),
        ),
    ]
