# Generated by Django 5.2.11 on 2026-08-08 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutes', '0003_institute_background_img_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='registration_officer',
            field=models.ForeignKey(blank=True, help_text='Employee whose name is shown as the admissions & registration manager on issued PDFs', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_officer_for', to=settings.AUTH_USER_MODEL, verbose_name='Registration Officer'),
        ),
    ]
