# Generated by Django 6.0.2 on 2026-02-21 08:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('institutes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('type', models.CharField(choices=[('diploma', 'Diploma'), ('course', 'Course')], max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Program Category',
                'verbose_name_plural': 'Program Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Diploma Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Diploma Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration_months', models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration (Months)')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('registration_start_date', models.DateField(verbose_name='Registration Start Date')),
                ('registration_end_date', models.DateField(verbose_name='Registration End Date')),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fees')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='institutes.institute', verbose_name='Institute')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diplomas', to='programs.programcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Diploma',
                'verbose_name_plural': 'Diplomas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Course Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('duration_months', models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration (Months)')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('registration_start_date', models.DateField(verbose_name='Registration Start Date')),
                ('registration_end_date', models.DateField(verbose_name='Registration End Date')),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fees')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='institutes.institute', verbose_name='Institute')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='programs.programcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='confirmed', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='clients.client', verbose_name='Client')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='programs.course', verbose_name='Course')),
                ('diploma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='programs.diploma', verbose_name='Diploma')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations_made', to=settings.AUTH_USER_MODEL, verbose_name='Registered By')),
            ],
            options={
                'verbose_name': 'Program Registration',
                'verbose_name_plural': 'Program Registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
