# Generated by Django 5.2.11 on 2026-04-26 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_clients_cli_nationa_62e969_idx_and_more'),
        ('institutes', '0003_institute_background_img_and_more'),
        ('programs', '0002_course_is_deleted_diploma_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='programs_co_code_194299_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['institute', 'status'], name='programs_co_institu_f7e831_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['start_date', 'end_date'], name='programs_co_start_d_8e7248_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_deleted'], name='programs_co_is_dele_39da97_idx'),
        ),
        migrations.AddIndex(
            model_name='diploma',
            index=models.Index(fields=['code'], name='programs_di_code_3f532a_idx'),
        ),
        migrations.AddIndex(
            model_name='diploma',
            index=models.Index(fields=['institute', 'status'], name='programs_di_institu_74dfd3_idx'),
        ),
        migrations.AddIndex(
            model_name='diploma',
            index=models.Index(fields=['start_date', 'end_date'], name='programs_di_start_d_52a580_idx'),
        ),
        migrations.AddIndex(
            model_name='diploma',
            index=models.Index(fields=['is_deleted'], name='programs_di_is_dele_4ebf61_idx'),
        ),
        migrations.AddIndex(
            model_name='programcategory',
            index=models.Index(fields=['type'], name='programs_pr_type_01acd3_idx'),
        ),
        migrations.AddIndex(
            model_name='programregistration',
            index=models.Index(fields=['client', 'status'], name='programs_pr_client__99dc06_idx'),
        ),
        migrations.AddIndex(
            model_name='programregistration',
            index=models.Index(fields=['diploma'], name='programs_pr_diploma_d735f9_idx'),
        ),
        migrations.AddIndex(
            model_name='programregistration',
            index=models.Index(fields=['course'], name='programs_pr_course__7af351_idx'),
        ),
        migrations.AddIndex(
            model_name='programregistration',
            index=models.Index(fields=['registered_by'], name='programs_pr_registe_756073_idx'),
        ),
        migrations.AddIndex(
            model_name='programregistration',
            index=models.Index(fields=['registration_date'], name='programs_pr_registr_f524e2_idx'),
        ),
    ]
