# Generated by Django 5.2.11 on 2026-08-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_course_programs_co_code_194299_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration (Text)'),
        ),
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hours'),
        ),
        migrations.AddField(
            model_name='course',
            name='study_mode',
            field=models.CharField(choices=[('offline', 'حضوري'), ('online', 'أونلاين'), ('both', 'حضوري أو أونلاين')], default='both', max_length=20, verbose_name='Study Mode'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration (Text)'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Hours'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='study_mode',
            field=models.CharField(choices=[('offline', 'حضوري'), ('online', 'أونلاين'), ('both', 'حضوري أو أونلاين')], default='both', max_length=20, verbose_name='Study Mode'),
        ),
        migrations.AddField(
            model_name='programregistration',
            name='study_mode',
            field=models.CharField(blank=True, choices=[('offline', 'حضوري'), ('online', 'أونلاين')], max_length=20, verbose_name='Study Mode'),
        ),
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registration_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration End Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='registration_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration Start Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='registration_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration End Date'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='registration_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Registration Start Date'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
