# Generated by Django 5.2.6 on 2025-09-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='identity_number',
            field=models.CharField(max_length=10, verbose_name='رقم الهوية'),
        ),
    ]
