# Generated by Django 5.2.6 on 2025-09-30 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_client_identity_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='added_by',
        ),
        migrations.AddField(
            model_name='clientdiploma',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='added_clients', to=settings.AUTH_USER_MODEL, verbose_name='تم الإضافة بواسطة'),
            preserve_default=False,
        ),
    ]
