# Generated by Django 5.2.6 on 2025-10-11 11:39

import User.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_remove_client_added_by_clientdiploma_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='مدة الدبلوم'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='duration_hours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عدد الساعات المعتمدة'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='end_date_gregorian',
            field=models.DateField(default=datetime.date.today, verbose_name='تاريخ نهاية الدبلوم (ميلادي)'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='end_date_hijri',
            field=models.CharField(default=User.models.default_hijri, max_length=10, verbose_name='تاريخ نهاية الدبلوم (هجري)'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='start_date_gregorian',
            field=models.DateField(default=datetime.date.today, verbose_name='تاريخ بداية الدبلوم (ميلادي)'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='start_date_hijri',
            field=models.CharField(default=User.models.default_hijri, max_length=10, verbose_name='تاريخ بداية الدبلوم (هجري)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sector',
            field=models.CharField(choices=[('mod', 'وزارة الدفاع'), ('moi', 'وزارة الداخلية'), ('emergency_forces', 'قوات الطوارئ الخاصة'), ('security_forces', 'قوات أمن المنشآت'), ('passports', 'الإدارة العامة للجوازات'), ('industrial_security', 'الهيئة العليا لأمن الصناعي'), ('royal_guard', 'الحرس الملكي السعودي'), ('national_guard', 'وزارة الحرس الوطني'), ('civil_defense', 'الدفاع المدني'), ('special_security_forces', 'قوات الأمن الخاصة'), ('drug_control', 'المديرية العامة لمكافحة المخدرات'), ('prisons', 'المديرية العامة للسجون'), ('aramco', 'أرامكو السعودية'), ('environmental_security', 'القوات الخاصة للأمن البيئي')], max_length=50, verbose_name='القطاع'),
        ),
        migrations.AlterField(
            model_name='clientdiploma',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_diplomas', to='User.client'),
        ),
    ]
