# Generated by Django 5.2.6 on 2025-10-13 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_diploma_duration_diploma_duration_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المعهد')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='clientdiploma',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='clientdiploma',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='User.institute', verbose_name='المعهد'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='clientdiploma',
            unique_together={('client', 'diploma', 'institute')},
        ),
    ]
