# Generated by Django 5.2.6 on 2025-11-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_institute_alter_clientdiploma_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdiploma',
            name='attendance_type',
            field=models.CharField(choices=[('online', 'أونلاين'), ('offline', 'حضوري')], default='offline', max_length=20, verbose_name='نوع حضور الطالب'),
        ),
        migrations.AddField(
            model_name='diploma',
            name='attendance_mode',
            field=models.CharField(choices=[('online', 'أونلاين فقط'), ('offline', 'حضوري فقط'), ('hybrid', 'هجين (أونلاين أو حضوري)')], default='hybrid', max_length=20, verbose_name='نظام الحضور للدبلوم'),
        ),
    ]
