# Generated by Django 5.2.6 on 2025-11-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_clientdiploma_attendance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdiploma',
            name='added_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
