# Generated by Django 5.2.6 on 2025-12-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_clientdiploma_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='area',
            field=models.CharField(max_length=50, verbose_name='المنطقة'),
        ),
    ]
