# Generated by Django 5.2.6 on 2025-12-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_client_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='diploma',
            name='type',
            field=models.CharField(choices=[('diploma', 'دبلوم'), ('cource', ' كورس')], default='cource', max_length=255, verbose_name='نوع '),
        ),
    ]
