# Generated by Django 5.2.6 on 2026-01-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_diploma_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.CharField(blank=True, choices=[('riyadh', 'فرع الرياض'), ('dammam', 'فرع الدمام'), ('arar', 'فرع عرعر'), ('hafr_al_batin', 'فرع حفر الباطن'), ('qassim', 'فرع القصيم'), ('khamis_mushait', 'فرع خميس مشيط')], max_length=50, null=True),
        ),
    ]
