# Generated by Django 5.2.6 on 2026-01-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_alter_user_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdiploma',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
