name: Deploy Elmashahed Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # 1. الدخول لمجلد المشروع الجديد
            cd /var/www/ElmashahedBackend
            
            # 2. تحديث الكود من Git
            git fetch origin main
            git reset --hard origin/main
            
            # 3. تفعيل البيئة الافتراضية وتحديث المكتبات
            source venv/bin/activate
            pip install -r requirements.txt
            
            # 4. تحديث قاعدة البيانات والملفات الثابتة
            python manage.py migrate
            python manage.py collectstatic --noinput
            
            # 5. إعادة تشغيل الخدمة الخاصة بهذا المشروع فقط (مهم جداً)
            sudo systemctl restart gunicorn_mashahed
            
            # 6. إعادة تشغيل Nginx (اختياري، لكن يفضل لضمان تحديث الـ Headers)
            sudo systemctl restart nginx